submission:
  destination: d0fe1fad-d6f1-4c67-b4e7-9d0ca6663bf3
  serviceType:
    urn: urn:de:fim:leika:leistung:99400048079000
    name: Simple Dummy Service
  jsonUri: https://schema.fitko.de/fim/s17000717_1.0.schema.json

callbackSecret: s3cr3t
